# Generated by Django 4.2.10 on 2025-03-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('product_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'PRODUCTGROUP',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_category_id', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
                ('product_group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.productgroup')),
            ],
            options={
                'db_table': 'PRODUCTS',
            },
        ),
        migrations.CreateModel(
            name='SalesHeader',
            fields=[
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('sale_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('payment_method', models.CharField(max_length=50)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
            ],
            options={
                'db_table': 'SALESHEADER',
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('sale_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('qty', models.BigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.products')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.salesheader')),
            ],
            options={
                'db_table': 'SALESLINE',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(default='', max_length=50)),
                ('category_value', models.CharField(default='', max_length=50)),
                ('category_name', models.CharField(default='0', max_length=50)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(auto_now=True)),
                ('update_tm', models.DateField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_marks', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'CATEGORY',
                'unique_together': {('category_type', 'category_value')},
            },
        ),
    ]
