# Generated by Django 4.2.10 on 2025-03-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
