# Generated by Django 4.2.10 on 2025-03-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
