# Generated by Django 4.2.10 on 2025-03-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_group_id',
        ),
        migrations.RemoveField(
            model_name='salesheader',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='sale_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='SalesHeader',
        ),
        migrations.DeleteModel(
            name='SalesLine',
        ),
    ]
