# Generated by Django 4.2.10 on 2025-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_branch_update_by_alter_branch_update_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
