# Generated by Django 4.2.10 on 2025-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_productgroup_product_image_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
    ]
