# Generated by Django 4.2.10 on 2025-04-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_salesheader_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='room',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.rooms'),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='table',
            field=models.ForeignKey(blank=True, db_column='table_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.tables'),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.vehicle'),
        ),
    ]
