# Generated by Django 4.2.10 on 2025-04-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_salesheader_room_salesheader_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chartofaccounts',
            table=None,
        ),
    ]
