# Generated by Django 4.2.10 on 2025-04-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_chartofaccounts_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chartofaccounts',
            table='CHARTOFACCOUNTS',
        ),
    ]
