# Generated by Django 4.2.10 on 2025-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_chartofaccounts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=22),
        ),
    ]
