# Generated by Django 4.2.10 on 2025-04-23 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_products_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ref_id', models.BigIntegerField(db_column='REFID', default=0)),
                ('ref_type', models.CharField(db_column='REFTYPE', default='', max_length=50)),
                ('ref_no', models.CharField(db_column='REFNO', default='', max_length=50)),
                ('remarks', models.CharField(default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('createdt', models.DateField(default=django.utils.timezone.now)),
                ('createtm', models.DateTimeField(default=django.utils.timezone.now)),
                ('createby', models.CharField(default='', max_length=10)),
                ('createremarks', models.CharField(default='', max_length=200)),
                ('updatedt', models.DateField(default='1900-01-01')),
                ('updatetm', models.DateField(default='1900-01-01')),
                ('updateby', models.CharField(default='', max_length=10)),
                ('updatemarks', models.CharField(default='', max_length=200)),
                ('branch', models.ForeignKey(db_column='BRANCHID', on_delete=django.db.models.deletion.CASCADE, to='pos.branch')),
                ('business_unit', models.ForeignKey(db_column='BUSINESSUNITID', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
                ('product', models.ForeignKey(db_column='ProductID', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.products')),
            ],
            options={
                'db_table': 'STOCKADJUSTMENT',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('poid', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order_date', models.DateField(default='1900-01-01')),
                ('expected_delivery_date', models.DateField(default='1900-01-01')),
                ('pono', models.CharField(default='', max_length=50)),
                ('postatus', models.CharField(default='', max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('createdt', models.DateField(default=django.utils.timezone.now)),
                ('createtm', models.DateTimeField(default=django.utils.timezone.now)),
                ('createby', models.CharField(default='', max_length=10)),
                ('createremarks', models.CharField(default='', max_length=200)),
                ('updatedt', models.DateField(default='1900-01-01')),
                ('updatetm', models.DateField(default='1900-01-01')),
                ('updateby', models.CharField(default='', max_length=10)),
                ('updatemarks', models.CharField(default='', max_length=200)),
                ('branch', models.ForeignKey(db_column='BRANCHID', on_delete=django.db.models.deletion.CASCADE, to='pos.branch')),
                ('business_unit', models.ForeignKey(db_column='BUSINESSUNITID', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
                ('supplier', models.ForeignKey(db_column='SupplierID', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.suppliers')),
            ],
            options={
                'db_table': 'PurchaseOrders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('line_total', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('createdt', models.DateField(default=django.utils.timezone.now)),
                ('createtm', models.DateTimeField(default=django.utils.timezone.now)),
                ('createby', models.CharField(default='', max_length=10)),
                ('createremarks', models.CharField(default='', max_length=200)),
                ('updatedt', models.DateField(default='1900-01-01')),
                ('updatetm', models.DateField(default='1900-01-01')),
                ('updateby', models.CharField(default='', max_length=10)),
                ('updatemarks', models.CharField(default='', max_length=200)),
                ('branch', models.ForeignKey(db_column='BRANCHID', on_delete=django.db.models.deletion.CASCADE, to='pos.branch')),
                ('business_unit', models.ForeignKey(db_column='BUSINESSUNITID', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
                ('poid', models.ForeignKey(db_column='POID', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.purchaseorders')),
                ('product', models.ForeignKey(db_column='ProductID', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.products')),
            ],
            options={
                'db_table': 'PurchaseOrderItems',
            },
        ),
    ]
