# Generated by Django 4.2.10 on 2025-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_stockadjustment_purchaseorders_purchaseorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='updatetm',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='poid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='updatetm',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatetm',
            field=models.DateTimeField(default='1900-01-01'),
        ),
    ]
