# Generated by Django 4.2.10 on 2025-04-23 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_purchaseorderitems_updatetm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='updatetm',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='updatetm',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatetm',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
