# Generated by Django 4.2.10 on 2025-04-24 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_purchaseorderitems_updatetm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('payment_ref', models.CharField(max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('createdt', models.DateField(default=django.utils.timezone.now)),
                ('createtm', models.DateTimeField(default=django.utils.timezone.now)),
                ('createby', models.CharField(default='', max_length=10)),
                ('createremarks', models.CharField(default='', max_length=200)),
                ('updatedt', models.DateField(default='1900-01-01')),
                ('updatetm', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('updateby', models.CharField(default='', max_length=10)),
                ('updatemarks', models.CharField(default='', max_length=200)),
                ('branch', models.ForeignKey(db_column='BRANCHID', on_delete=django.db.models.deletion.CASCADE, to='pos.branch')),
                ('business_unit', models.ForeignKey(db_column='BUSINESSUNITID', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
                ('supplier', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.CASCADE, to='pos.suppliers')),
            ],
            options={
                'db_table': 'SUPPLIERPAYMENTS',
            },
        ),
    ]
