# Generated by Django 4.2.10 on 2025-04-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='business_unit',
            field=models.ForeignKey(db_column='business_unit_id', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.products'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='business_unit',
            field=models.ForeignKey(db_column='business_unit_id', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='business_unit',
            field=models.ForeignKey(db_column='business_unit_id', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.products'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='business_unit',
            field=models.ForeignKey(db_column='business_unit_id', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit'),
        ),
    ]
