# Generated by Django 4.2.10 on 2025-04-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_alter_purchaseorderitems_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitems',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchaseorders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'managed': False},
        ),
    ]
