# Generated by Django 4.2.10 on 2025-04-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_alter_purchaseorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={},
        ),
    ]
