# Generated by Django 4.2.10 on 2025-04-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_alter_purchaseorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryheader',
            options={'managed': False},
        ),
    ]
