# Generated by Django 4.2.10 on 2025-04-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_alter_inventoryheader_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryheader',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryheader',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='inventoryheader',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='inventoryheader',
            name='grnno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryheader',
            name='ref_dt',
            field=models.DateField(db_column='REFDT', default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='inventoryheader',
            name='ref_no',
            field=models.CharField(db_column='REFNO', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryheader',
            name='ref_type',
            field=models.CharField(db_column='REFTYPE', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='branch',
            field=models.ForeignKey(db_column='BRANCHID', on_delete=django.db.models.deletion.CASCADE, to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='business_unit',
            field=models.ForeignKey(db_column='BUSINESSUNITID', on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='create_by',
            field=models.CharField(db_column='CREATEBY', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='create_dt',
            field=models.DateField(auto_now_add=True, db_column='CREATEDT'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='create_remarks',
            field=models.CharField(db_column='CREATEREMARKS', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='create_tm',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATETM'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='net_value',
            field=models.DecimalField(db_column='NETVALUE', decimal_places=3, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='update_by',
            field=models.CharField(db_column='UPDATEBY', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='update_dt',
            field=models.DateField(db_column='UPDATEDT', default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='update_marks',
            field=models.CharField(db_column='UPDATEMARKS', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='update_tm',
            field=models.DateField(db_column='UPDATETM', default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='inventoryheader',
            name='warehouse',
            field=models.ForeignKey(db_column='WAREHOUSEID', on_delete=django.db.models.deletion.CASCADE, to='pos.warehouse'),
        ),
    ]
