# Generated by Django 4.2.10 on 2025-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_alter_inventoryheader_grnno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='pono',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
