# Generated by Django 4.2.10 on 2025-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_products_category_alter_products_update_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='update_tm',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
