# Generated by Django 4.2.10 on 2025-05-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentries',
            name='card_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentries',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]



