# Generated by Django 4.2.10 on 2025-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_journalentries_card_no_journalentries_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesheader',
            name='update_marks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
