# Generated by Django 4.2.10 on 2025-06-18 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_alter_salesheader_update_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesheader',
            name='update_tm',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
