# Generated by Django 4.2.10 on 2025-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_alter_salesheader_update_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesheader',
            name='update_tm',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
