# Generated by Django 4.2.10 on 2025-06-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_alter_salesheader_update_tm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='updatedt',
            new_name='update_dt',
        ),
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='updatedt',
            new_name='update_dt',
        ),
    ]
