# Generated by Django 4.2.10 on 2025-06-18 08:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_alter_salesheader_update_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='updateby',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatedt',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatemarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_ref',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updateby',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updatedt',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updatemarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
