# Generated by Django 4.2.10 on 2025-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_alter_stockadjustment_updateby_and_more'),
        ('pos', '0038_rename_updatedt_stockadjustment_update_dt_and_more'),
    ]

    operations = [
    ]
