# Generated by Django 4.2.10 on 2025-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_merge_20250618_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='update_dt',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='update_dt',
        ),
    ]
