# Generated by Django 4.2.10 on 2025-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_remove_stockadjustment_update_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='updateby',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatedt',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='updatemarks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_ref',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updateby',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updatedt',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updatemarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
