# Generated by Django 4.2.23 on 2025-10-12 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_alter_stockadjustment_updateby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhaar_card_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_dt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_tm',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone1', models.DecimalField(decimal_places=0, default=0, max_digits=22)),
                ('booking_agent_code', models.CharField(default='', max_length=150)),
                ('booking_agent_dt', models.DateField(default='1900-01-01')),
                ('booking_agent_ref_no', models.CharField(default='', max_length=100)),
                ('start_dt', models.DateField(default='1900-01-01')),
                ('end_dt', models.DateField(default='1900-01-01')),
                ('start_tm', models.DateTimeField(default='1900-01-01 00:00:00')),
                ('end_tm', models.DateTimeField(default='1900-01-01 00:00:00')),
                ('no_of_rooms', models.DecimalField(decimal_places=0, default=0, max_digits=22)),
                ('no_of_guest', models.DecimalField(decimal_places=0, default=0, max_digits=22)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=22)),
                ('create_dt', models.DateField(default='1900-01-01')),
                ('create_tm', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=10)),
                ('create_remarks', models.CharField(default='', max_length=200)),
                ('update_dt', models.DateField(default='1900-01-01')),
                ('update_tm', models.DateTimeField(default='1900-01-01 00:00:00')),
                ('update_by', models.CharField(default='', max_length=10)),
                ('update_remarks', models.CharField(default='', max_length=200)),
                ('booking_dt', models.DateField(default='1900-01-01')),
                ('booking_status', models.CharField(default='00', max_length=10)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rooms')),
            ],
            options={
                'db_table': 'REGISTRATION',
                'unique_together': {('business_unit', 'booking_id')},
            },
        ),
        migrations.AddField(
            model_name='salesheader',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.registration'),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_type', models.CharField(db_column='AUTYPE', default='', max_length=50)),
                ('saas_username', models.CharField(default='', max_length=50)),
                ('au_menu', models.CharField(db_column='AUMENU', default='', max_length=200)),
                ('au_submenu', models.CharField(db_column='AUSUBMENU', default='', max_length=200)),
                ('au_menu_text', models.CharField(db_column='AUMENUTEXT', default='', max_length=200)),
                ('au_submenu_text', models.CharField(db_column='AUSUBMENUTEXT', default='', max_length=200)),
                ('au_status', models.CharField(db_column='AUSTATUS', default='', max_length=10)),
                ('au_create_dt', models.DateTimeField(db_column='AUCREATEDT', default='1900-01-01')),
                ('au_create_tm', models.DateTimeField(db_column='AUCREATETM', default='1900-01-01')),
                ('au_create_by', models.CharField(db_column='AUCREATEBY', default='', max_length=10)),
                ('au_create_remarks', models.CharField(db_column='AUCREATEREMARKS', default='', max_length=250)),
                ('au_update_dt', models.DateTimeField(db_column='AUUPDATEDT', default='1900-01-01')),
                ('au_update_tm', models.DateTimeField(db_column='AUUPDATETM', default='1900-01-01')),
                ('au_update_by', models.CharField(db_column='AUUPDATEBY', default='', max_length=10)),
                ('au_update_remarks', models.CharField(db_column='AUUPDATEREMARKS', default='', max_length=250)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.businessunit')),
            ],
            options={
                'db_table': 'AUTHORITY',
                'unique_together': {('business_unit', 'au_type', 'saas_username', 'au_menu', 'au_submenu')},
            },
        ),
    ]
